////
////  BirdEggDatabase.swift
////  EggAi
////
////  Created by Mihail Ozun on 11.08.2025.
////
//
//import Foundation
//
//struct BirdEggDatabase {
//    static let eggs: [BirdEgg] = [
//        BirdEgg(id: 1, name: "American Robin", scientificName: "Turdus migratorius", image: "american_robin_egg", eggColor: "Sky blue", eggSize: "2.8-3.0 cm", description: "One of the most recognizable bird eggs with its distinctive blue color. Typically lays 3-5 eggs per clutch.", habitat: "Gardens, parks, forests", region: "North America"),
//        BirdEgg(id: 2, name: "House Sparrow", scientificName: "Passer domesticus", image: "house_sparrow_egg", eggColor: "White with brown spots", eggSize: "2.0-2.2 cm", description: "Small eggs with variable brown markings. Common in urban areas worldwide.", habitat: "Urban areas, farms", region: "Worldwide"),
//        BirdEgg(id: 3, name: "Blue Jay", scientificName: "Cyanocitta cristata", image: "blue_jay_egg", eggColor: "Olive with brown spots", eggSize: "2.5-3.0 cm", description: "Eggs have olive or buff base color with brown or gray spots concentrated at the larger end.", habitat: "Deciduous forests, parks", region: "Eastern North America"),
//        BirdEgg(id: 4, name: "Northern Cardinal", scientificName: "Cardinalis cardinalis", image: "cardinal_egg", eggColor: "Grayish white with spots", eggSize: "2.2-2.7 cm", description: "Pale bluish or greenish white eggs with brown, purple, or gray spots.", habitat: "Woodland edges, gardens", region: "Eastern United States"),
//        BirdEgg(id: 5, name: "Mourning Dove", scientificName: "Zenaida macroura", image: "mourning_dove_egg", eggColor: "Pure white", eggSize: "2.6-3.0 cm", description: "Plain white eggs, typically two per clutch. One of the most prolific bird species.", habitat: "Open areas, urban settings", region: "North America"),
//        BirdEgg(id: 6, name: "European Starling", scientificName: "Sturnus vulgaris", image: "starling_egg", eggColor: "Glossy blue-green", eggSize: "2.7-3.2 cm", description: "Beautiful pale blue or green eggs without markings. Introduced species in many regions.", habitat: "Urban areas, farmland", region: "Europe, North America"),
//        BirdEgg(id: 7, name: "House Finch", scientificName: "Haemorhous mexicanus", image: "house_finch_egg", eggColor: "Bluish white with spots", eggSize: "1.6-2.1 cm", description: "Pale blue eggs with black and lavender dots concentrated at the larger end.", habitat: "Urban areas, desert", region: "Western North America"),
//        BirdEgg(id: 8, name: "Common Blackbird", scientificName: "Turdus merula", image: "blackbird_egg", eggColor: "Blue-green with spots", eggSize: "2.6-3.2 cm", description: "Greenish-blue eggs with reddish-brown speckles. Related to the American Robin.", habitat: "Gardens, woodlands", region: "Europe, Asia"),
//        BirdEgg(id: 9, name: "Great Tit", scientificName: "Parus major", image: "great_tit_egg", eggColor: "White with red spots", eggSize: "1.6-1.8 cm", description: "White eggs with reddish-brown spots. One of Europe's most common garden birds.", habitat: "Woodlands, gardens", region: "Europe, Asia"),
//        BirdEgg(id: 10, name: "Barn Swallow", scientificName: "Hirundo rustica", image: "barn_swallow_egg", eggColor: "White with brown spots", eggSize: "1.7-2.0 cm", description: "Cream-colored eggs with brown speckles. Found in open barns and under bridges.", habitat: "Open areas near water", region: "Worldwide"),
//        BirdEgg(id: 11, name: "Eastern Bluebird", scientificName: "Sialia sialis", image: "eastern_bluebird_egg", eggColor: "Pale blue", eggSize: "2.1-2.3 cm", description: "Beautiful unmarked pale blue eggs. Occasionally white eggs occur.", habitat: "Open woodlands, fields", region: "Eastern North America"),
//        BirdEgg(id: 12, name: "American Goldfinch", scientificName: "Spinus tristis", image: "goldfinch_egg", eggColor: "Pale bluish white", eggSize: "1.6-1.8 cm", description: "Very pale blue, almost white eggs. Unmarked and translucent when fresh.", habitat: "Fields, gardens", region: "North America"),
//        BirdEgg(id: 13, name: "Killdeer", scientificName: "Charadrius vociferus", image: "killdeer_egg", eggColor: "Buff with black spots", eggSize: "3.5-3.7 cm", description: "Heavily spotted eggs that blend perfectly with gravel. Laid directly on ground.", habitat: "Open ground, gravel", region: "Americas"),
//        BirdEgg(id: 14, name: "Canada Goose", scientificName: "Branta canadensis", image: "canada_goose_egg", eggColor: "Creamy white", eggSize: "8.0-9.0 cm", description: "Large cream-colored eggs. Nests near water and fiercely protects eggs.", habitat: "Lakes, rivers, parks", region: "North America"),
//        BirdEgg(id: 15, name: "Mallard", scientificName: "Anas platyrhynchos", image: "mallard_egg", eggColor: "Pale green to white", eggSize: "5.0-6.0 cm", description: "Light greenish or grayish eggs. The most common duck in the world.", habitat: "Wetlands, parks", region: "Northern Hemisphere"),
//        BirdEgg(id: 16, name: "Rock Pigeon", scientificName: "Columba livia", image: "pigeon_egg", eggColor: "White", eggSize: "3.8-4.0 cm", description: "Pure white eggs, usually two per clutch. Common in cities worldwide.", habitat: "Urban areas", region: "Worldwide"),
//        BirdEgg(id: 17, name: "Bald Eagle", scientificName: "Haliaeetus leucocephalus", image: "bald_eagle_egg", eggColor: "Off-white", eggSize: "7.0-8.0 cm", description: "Large white eggs laid in massive stick nests. America's national bird.", habitat: "Near large water bodies", region: "North America"),
//        BirdEgg(id: 18, name: "Great Horned Owl", scientificName: "Bubo virginianus", image: "great_horned_owl_egg", eggColor: "White", eggSize: "5.0-5.5 cm", description: "Round white eggs. One of the earliest nesting birds, often laying eggs in winter.", habitat: "Forests, urban areas", region: "Americas"),
//        BirdEgg(id: 19, name: "Ruby-throated Hummingbird", scientificName: "Archilochus colubris", image: "hummingbird_egg", eggColor: "White", eggSize: "1.2-1.4 cm", description: "Tiny white eggs the size of peas. Among the smallest bird eggs in the world.", habitat: "Gardens, forest edges", region: "Eastern North America"),
//        BirdEgg(id: 20, name: "Common Raven", scientificName: "Corvus corax", image: "raven_egg", eggColor: "Green with brown marks", eggSize: "4.5-5.5 cm", description: "Greenish eggs with brown and gray blotches. Highly intelligent birds.", habitat: "Mountains, forests", region: "Northern Hemisphere"),
//        // Add more to reach 30 for better performance
//        BirdEgg(id: 21, name: "European Robin", scientificName: "Erithacus rubecula", image: "european_robin_egg", eggColor: "White with red spots", eggSize: "1.9-2.2 cm", description: "Cream or buff eggs with reddish speckles. Britain's national bird.", habitat: "Gardens, woodlands", region: "Europe"),
//        BirdEgg(id: 22, name: "Chicken", scientificName: "Gallus gallus domesticus", image: "chicken_egg", eggColor: "White to brown", eggSize: "5.0-6.0 cm", description: "Familiar farm eggs varying from white to brown depending on breed.", habitat: "Farms, backyards", region: "Worldwide"),
//        BirdEgg(id: 23, name: "Ostrich", scientificName: "Struthio camelus", image: "ostrich_egg", eggColor: "Cream", eggSize: "15-18 cm", description: "The largest bird eggs in the world. Can weigh up to 1.4 kg.", habitat: "Savannas, deserts", region: "Africa"),
//        BirdEgg(id: 24, name: "Song Sparrow", scientificName: "Melospiza melodia", image: "song_sparrow_egg", eggColor: "Greenish white with spots", eggSize: "1.9-2.5 cm", description: "Heavily spotted eggs with brown and purple marks on greenish background.", habitat: "Brushy areas, marshes", region: "North America"),
//        BirdEgg(id: 25, name: "Barn Owl", scientificName: "Tyto alba", image: "barn_owl_egg", eggColor: "White", eggSize: "3.8-4.4 cm", description: "Pure white, slightly elongated eggs. Often found in old barns and buildings.", habitat: "Open habitats, farms", region: "Worldwide"),
//        BirdEgg(id: 26, name: "Black-capped Chickadee", scientificName: "Poecile atricapillus", image: "chickadee_egg", eggColor: "White with red spots", eggSize: "1.5-1.6 cm", description: "Tiny white eggs with fine reddish-brown dots, especially at larger end.", habitat: "Deciduous forests", region: "Northern North America"),
//        BirdEgg(id: 27, name: "Red-winged Blackbird", scientificName: "Agelaius phoeniceus", image: "redwinged_blackbird_egg", eggColor: "Pale blue-green with marks", eggSize: "2.4-2.6 cm", description: "Pale bluish or greenish eggs with dark scrawls and spots.", habitat: "Marshes, wetlands", region: "North America"),
//        BirdEgg(id: 28, name: "Wild Turkey", scientificName: "Meleagris gallopavo", image: "wild_turkey_egg", eggColor: "Tan with brown spots", eggSize: "6.0-7.0 cm", description: "Buff-colored eggs with reddish-brown speckles. Laid on ground in hidden nests.", habitat: "Forests, fields", region: "North America"),
//        BirdEgg(id: 29, name: "Peregrine Falcon", scientificName: "Falco peregrinus", image: "peregrine_falcon_egg", eggColor: "Cream with red marks", eggSize: "5.0-5.2 cm", description: "Heavily marked eggs with reddish-brown blotches. World's fastest bird.", habitat: "Cliffs, cities", region: "Worldwide"),
//        BirdEgg(id: 30, name: "Common Loon", scientificName: "Gavia immer", image: "loon_egg", eggColor: "Olive brown with spots", eggSize: "8.9-9.0 cm", description: "Large olive-brown eggs with dark spots. Known for haunting calls.", habitat: "Northern lakes", region: "Northern North America")
//    ]
//}
